// <auto-generated />
using System;
using BondAnalyzer.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BondAnalyzer.API.Migrations
{
    [DbContext(typeof(BondDbContext))]
    [Migration("20260407022331_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BondAnalyzer.API.Models.Bono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuponesPorAnio")
                        .HasColumnType("int");

                    b.Property<decimal>("DuracionMacaulay")
                        .HasColumnType("DECIMAL(10,4)");

                    b.Property<decimal>("DuracionModificada")
                        .HasColumnType("DECIMAL(10,4)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("GspAbsoluto")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("GspRelativo")
                        .HasColumnType("DECIMAL(10,6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Plazo")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioCalculado")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("RentabilidadExigida")
                        .HasColumnType("DECIMAL(10,6)");

                    b.Property<decimal>("TasaCupon")
                        .HasColumnType("DECIMAL(10,6)");

                    b.Property<decimal>("TirComprador")
                        .HasColumnType("DECIMAL(10,6)");

                    b.Property<decimal>("TirOriginal")
                        .HasColumnType("DECIMAL(10,6)");

                    b.Property<decimal>("ValorNominal")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Bonos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
